<?php

return [
    'permissions' => [
        [
            'code' => 'dashboard.view',
            'name' => 'Lihat Dashboard',
            'module' => 'Utama',
            'route' => 'dashboard',
            'action' => 'view',
        ],
        [
            'code' => 'documents.inbox.view',
            'name' => 'Lihat Inbox Approval',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.inbox',
            'action' => 'view',
        ],
        [
            'code' => 'documents.create.create',
            'name' => 'Tambah Dokumen',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.create',
            'action' => 'create',
        ],
        [
            'code' => 'documents.master.view',
            'name' => 'Lihat Dokumen Master',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.master',
            'action' => 'view',
        ],
        [
            'code' => 'document-templates.view',
            'name' => 'Lihat Template Dokumen',
            'module' => 'Manajemen Dokumen',
            'route' => 'document-templates.index',
            'action' => 'view',
        ],
        [
            'code' => 'document-templates.edit',
            'name' => 'Edit Template Dokumen',
            'module' => 'Manajemen Dokumen',
            'route' => 'document-templates.index',
            'action' => 'edit',
        ],
        [
            'code' => 'reports.view',
            'name' => 'Lihat Reporting',
            'module' => 'Reporting',
            'route' => 'reports.index',
            'action' => 'view',
        ],
        [
            'code' => 'users.manage',
            'name' => 'Kelola User',
            'module' => 'Administrasi',
            'route' => 'users.index',
            'action' => 'manage',
        ],
        [
            'code' => 'access-groups.manage',
            'name' => 'Kelola Group Akses',
            'module' => 'Administrasi',
            'route' => 'access-groups.index',
            'action' => 'manage',
        ],
        [
            'code' => 'access-menus.view',
            'name' => 'Lihat Menu Akses',
            'module' => 'Administrasi',
            'route' => 'access-menus.index',
            'action' => 'view',
        ],
        [
            'code' => 'approval-flows.manage',
            'name' => 'Kelola Approval Flow',
            'module' => 'Administrasi',
            'route' => 'approval-flows.index',
            'action' => 'manage',
        ],
        [
            'code' => 'master-data.process-functions.manage',
            'name' => 'Kelola Proses / Fungsi',
            'module' => 'Master Data',
            'route' => 'master-data.process-functions',
            'action' => 'manage',
        ],
        [
            'code' => 'master-data.business-processes.manage',
            'name' => 'Kelola Proses Bisnis',
            'module' => 'Master Data',
            'route' => 'master-data.business-processes',
            'action' => 'manage',
        ],
        [
            'code' => 'master-data.departments.manage',
            'name' => 'Kelola Department',
            'module' => 'Master Data',
            'route' => 'master-data.departments',
            'action' => 'manage',
        ],
        [
            'code' => 'master-data.document-types.manage',
            'name' => 'Kelola Jenis Dokumen',
            'module' => 'Master Data',
            'route' => 'master-data.document-types',
            'action' => 'manage',
        ],
        [
            'code' => 'activity-log.view',
            'name' => 'Lihat Catatan Aktivitas',
            'module' => 'Log',
            'route' => 'activity-log.index',
            'action' => 'view',
        ],
    ],
];
