<?php

$crudPermissions = fn (string $codePrefix, string $featureName, string $module, string $route): array => [
    [
        'code' => "{$codePrefix}.view",
        'name' => "Lihat {$featureName}",
        'module' => $module,
        'route' => $route,
        'action' => 'view',
    ],
    [
        'code' => "{$codePrefix}.create",
        'name' => "Tambah {$featureName}",
        'module' => $module,
        'route' => $route,
        'action' => 'create',
    ],
    [
        'code' => "{$codePrefix}.update",
        'name' => "Ubah {$featureName}",
        'module' => $module,
        'route' => $route,
        'action' => 'update',
    ],
    [
        'code' => "{$codePrefix}.delete",
        'name' => "Hapus {$featureName}",
        'module' => $module,
        'route' => $route,
        'action' => 'delete',
    ],
];

return [
    'permissions' => [
        [
            'code' => 'dashboard.view',
            'name' => 'Lihat Dashboard',
            'module' => 'Utama',
            'route' => 'dashboard',
            'action' => 'view',
        ],
        [
            'code' => 'documents.inbox.view',
            'name' => 'Lihat Inbox Approval',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.inbox',
            'action' => 'view',
        ],
        [
            'code' => 'documents.approval.view',
            'name' => 'Lihat Detail Approval Dokumen',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.approval.show',
            'action' => 'view',
        ],
        [
            'code' => 'documents.approval.download',
            'name' => 'Download File Approval Dokumen',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.approval.files.show',
            'action' => 'download',
        ],
        [
            'code' => 'documents.approval.preview',
            'name' => 'Preview File Approval Dokumen',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.approval.files.preview',
            'action' => 'preview',
        ],
        [
            'code' => 'documents.create.view',
            'name' => 'Lihat Tambah Dokumen',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.create',
            'action' => 'view',
        ],
        [
            'code' => 'documents.create.create',
            'name' => 'Submit Tambah Dokumen',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.store',
            'action' => 'create',
        ],
        [
            'code' => 'documents.master.view',
            'name' => 'Lihat Dokumen Master',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.master',
            'action' => 'view',
        ],
        [
            'code' => 'documents.obsolete.view',
            'name' => 'Lihat Dokumen Obsolete',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.obsolete',
            'action' => 'view',
        ],
        [
            'code' => 'documents.obsolete.create',
            'name' => 'Tambah Dokumen Obsolete',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.obsolete',
            'action' => 'create',
        ],
        [
            'code' => 'documents.obsolete.restore',
            'name' => 'Jadikan Master Dokumen Obsolete',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.master.restore',
            'action' => 'restore',
        ],
        [
            'code' => 'documents.approval.assign',
            'name' => 'Assign Approver Dokumen',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.approval.assign',
            'action' => 'assign',
        ],
        [
            'code' => 'document-templates.view',
            'name' => 'Lihat Template Dokumen',
            'module' => 'Manajemen Dokumen',
            'route' => 'document-templates.index',
            'action' => 'view',
        ],
        [
            'code' => 'document-templates.download',
            'name' => 'Download Template Dokumen',
            'module' => 'Manajemen Dokumen',
            'route' => 'document-templates.files.show',
            'action' => 'download',
        ],
        [
            'code' => 'document-templates.edit',
            'name' => 'Edit Template Dokumen',
            'module' => 'Manajemen Dokumen',
            'route' => 'document-templates.index',
            'action' => 'edit',
        ],
        [
            'code' => 'document-templates.delete',
            'name' => 'Delete',
            'module' => 'Manajemen Dokumen',
            'route' => 'document-templates.index',
            'action' => 'delete',
        ],
        [
            'code' => 'reports.view',
            'name' => 'Lihat Reporting',
            'module' => 'Reporting',
            'route' => 'reports.index',
            'action' => 'view',
        ],
        ...$crudPermissions('users', 'User', 'Administrasi', 'users.index'),
        ...$crudPermissions('access-groups', 'Group Akses', 'Administrasi', 'access-groups.index'),
        [
            'code' => 'access-menus.view',
            'name' => 'Lihat Menu Akses',
            'module' => 'Administrasi',
            'route' => 'access-menus.index',
            'action' => 'view',
        ],
        ...$crudPermissions('approval-flows', 'Approval Flow', 'Administrasi', 'approval-flows.index'),
        ...$crudPermissions('master-data.process-functions', 'Proses / Fungsi', 'Master Data', 'master-data.process-functions'),
        ...$crudPermissions('master-data.business-processes', 'Proses Bisnis', 'Master Data', 'master-data.business-processes'),
        ...$crudPermissions('master-data.departments', 'Department', 'Master Data', 'master-data.departments'),
        ...$crudPermissions('master-data.document-types', 'Jenis Dokumen', 'Master Data', 'master-data.document-types'),
        [
            'code' => 'activity-log.view',
            'name' => 'Lihat Catatan Aktivitas',
            'module' => 'Log',
            'route' => 'activity-log.index',
            'action' => 'view',
        ],
    ],
];
